/**
 * Stargate Plugin Types
 */

// ============================================
// Tab System Types
// ============================================

/**
 * 고정 사이트 (설정에서 등록, 닫기 불가)
 */
export interface PinnedSite {
    id: string              // 고유 ID (uuid)
    name: string            // 사이트 이름 (툴팁용)
    url: string             // URL
    favicon?: string        // 커스텀 favicon URL (optional)
    profileKey: string      // 세션 분리용 키
}

/**
 * 임시 탭 (새 탭으로 추가, 닫기 가능)
 */
export interface TempTab {
    id: string              // 'temp-{timestamp}'
    url: string
    title: string
    profileKey: string
}

/**
 * 현재 활성 탭 상태
 */
export interface TabState {
    id: string
    url: string
    title: string
    isPinned: boolean
}

// ============================================
// AI Types
// ============================================

/**
 * AI Provider 타입
 */
export type AIProviderType = 'openai' | 'anthropic' | 'gemini' | 'zai' | 'ollama'

/**
 * AI 설정
 */
export interface AISettings {
    provider: AIProviderType
    apiKeys: Partial<Record<AIProviderType, string>>
    models: Partial<Record<AIProviderType, string>>
    maxTokens: number
    defaultLanguage: string
    defaultTemplate: TemplateType  // 빠른 분석용 기본 템플릿
    autoTags: boolean
    notesFolder: string
    noteTemplate: string  // 노트 템플릿 (변수: {{title}}, {{source}}, {{date}}, {{template}}, {{provider}}, {{content}}, {{original}})
}

/**
 * 분석 템플릿 타입
 */
export type TemplateType =
    | 'briefing'
    | 'concept'
    | 'insight'
    | 'knowledge-map'
    | 'deep-analysis'
    | 'meta-hub'
    | 'comprehensive'

/**
 * 분석 템플릿 정의
 */
export interface AnalysisTemplate {
    id: TemplateType
    name: string
    icon: string
    description: string
    systemPrompt: string
    userPromptTemplate: string
}

/**
 * 사용자 저장 프롬프트
 * - systemPrompt가 있으면: 전체 템플릿 (템플릿 버튼 영역에 표시)
 * - systemPrompt가 없으면: 빠른 프롬프트 (커스텀 프롬프트 탭에 표시)
 */
export interface SavedPrompt {
    id: string              // 'custom-{timestamp}'
    name: string
    prompt: string          // user prompt
    systemPrompt?: string   // system prompt (있으면 전체 템플릿)
    icon?: string           // 아이콘 (전체 템플릿용)
}

/**
 * 사용자 정의 템플릿 (기본 템플릿 오버라이드)
 */
export interface CustomTemplate {
    id: TemplateType        // 기본 템플릿 ID
    systemPrompt: string    // 사용자 정의 시스템 프롬프트
    userPromptTemplate: string  // 사용자 정의 사용자 프롬프트
}

/**
 * 분석 설정
 */
export interface AnalysisConfig {
    templateId: TemplateType | null
    customPrompt: string | null
    provider: AIProviderType
    language: string
}

// ============================================
// Plugin Settings
// ============================================

/**
 * 플러그인 설정
 */
export interface PluginSettings {
    uuid: string
    pinnedSites: PinnedSite[]       // 고정 사이트 (최대 5개)
    tempTabs: TempTab[]             // 현재 열린 임시 탭
    activeTabId: string             // 현재 활성 탭 ID
    ai: AISettings
    savedPrompts: SavedPrompt[]
    customTemplates: CustomTemplate[]  // 사용자 정의 템플릿
}

/**
 * 기본 노트 템플릿
 */
export const DEFAULT_NOTE_TEMPLATE = `---
source: "{{source}}"
created: {{date}}
template: {{template}}
{{#provider}}provider: {{provider}}{{/provider}}
{{#model}}model: {{model}}{{/model}}
{{#channel}}channel: "{{channel}}"{{/channel}}
{{#duration}}duration: "{{duration}}"{{/duration}}
{{#videoType}}videoType: "{{videoType}}"{{/videoType}}
{{#videoTags}}videoTags: [{{videoTags}}]{{/videoTags}}
tags: [stargate/clipping]
---

# {{title}}

> Source: {{source}}
{{#channel}}> Channel: {{channel}}{{/channel}}
{{#duration}}> Duration: {{duration}}{{/duration}}

---

{{content}}

{{#original}}
---

## Original Content

{{original}}
{{/original}}

---

*Generated by Star Gate*
`

/**
 * 기본 AI 설정
 */
export const DEFAULT_AI_SETTINGS: AISettings = {
    provider: 'openai',
    apiKeys: {},
    models: {
        openai: 'gpt-4o',
        anthropic: 'claude-sonnet-4-20250514',
        gemini: 'gemini-2.0-flash',
        zai: 'glm-4-flash',
        ollama: 'llama3.2'
    },
    maxTokens: 64000,
    defaultLanguage: 'ko',
    defaultTemplate: 'briefing',
    autoTags: true,
    notesFolder: 'Clippings',
    noteTemplate: DEFAULT_NOTE_TEMPLATE
}

/**
 * 기본 플러그인 설정
 */
export const DEFAULT_SETTINGS: PluginSettings = {
    uuid: '',
    pinnedSites: [],
    tempTabs: [],
    activeTabId: '',
    ai: DEFAULT_AI_SETTINGS,
    savedPrompts: [],
    customTemplates: []
}
